name: github pages

on:
  push:
    branches:
      - main  # or replace 'main' with the name of your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.89.4' # replace with the version of Hugo you are using

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages  # deploy to the gh-pages branch